[platformio]
default_envs = fsr_leonardo
src_dir = main
data_dir = esp32c6-bridge/data

[env]
framework = arduino
monitor_speed = 115200

[env:fsr_leonardo]
platform = atmelavr
board = leonardo
build_src_filter =
  -<*>
  +<fsr/main.cpp>
lib_extra_dirs =
  $PROJECT_PACKAGES_DIR/framework-arduino-avr/libraries
build_flags =
  -I$PROJECT_PACKAGES_DIR/framework-arduino-avr/libraries/EEPROM/src
lib_deps =
  https://github.com/MHeironimus/ArduinoJoystickLibrary.git#v2.1.1

[env:fsr_teensy40]
platform = teensy
board = teensy40
build_src_filter =
  -<*>
  +<fsr/main.cpp>
lib_extra_dirs =
  $PROJECT_PACKAGES_DIR/framework-arduinoteensy/libraries
build_flags =
  -I$PROJECT_PACKAGES_DIR/framework-arduinoteensy/libraries/EEPROM
  -D USB_SERIAL_HID

[env:esp32c6_bridge]
platform = espressif32
board = seeed_xiao_esp32c6
framework = espidf
board_build.partitions = esp32c6-bridge/partitions.csv
build_flags =
  -Iesp32c6-bridge